version: '3'

services:
  node-server:
    image: poperlo/server
    mem_limit: 128m
    hostname: node-server
    environment:
      REDIS_HOST: $REDIS_HOST
      REDIS_PORT: $REDIS_PORT
      PGUSER: $PGUSER
      PGPASSWORD: $PGPASSWORD
      PGHOST: $PGHOST
      PGPORT: $PGPORT
      PGDATABASE: $PGDATABASE

  node-client:
    image: poperlo/client
    mem_limit: 128m
    hostname: node-client

  node-worker:
    image: poperlo/worker
    mem_limit: 128m
    hostname: node-worker
    environment:
      REDIS_HOST: $REDIS_HOST
      REDIS_PORT: $REDIS_PORT

  nginx:
    depends_on:
      - node-client
      - node-server
    image: poperlo/nginx
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"